#!/usr/bin/env bash

set -o errtrace

shopt -s extglob

cp -a `dirname $BASH_SOURCE` ~/.hereos/
cp -a `dirname $BASH_SOURCE`/../config ~/.hereos/
cp -a `dirname $BASH_SOURCE`/../server_template ~/.hereos/
cp -a `dirname $BASH_SOURCE`/../client_template ~/.hereos/
cp -a `dirname $BASH_SOURCE`/../yocto_template ~/.hereos/
cp -a `dirname $BASH_SOURCE`/../patches ~/.hereos/

echo "HereOS SDK is installed"
echo "Run:"
echo ""
echo "  . ~/.hereos/scripts/register"
echo ""
echo "To load the SDK into your environment"
